### ISSUE TITLE
pve: Enterprise url for repo doesn't match PVE 7

### ISSUE THREAD

**Issue by rasmuslp** [maxhoesel-ansible/ansible-collection-proxmox#98]
On a fresh install of Proxmox VE 7.2-3 running `maxhoesel.proxmox.pve` 5.0.1 with all defaults, I get an unexpected result with how the repository urls gets handled.

It correctly adds `pve-no-subscription`, but fails to remove / disable `pve-enterprise`, as the url is `https://enterprise.proxmox.com/debian/pve`.

This causes it to fail updating the APT cache as it's unauthorised for the enterprise repo.

**Comment by maxhoesel** [comment]
Thanks for the bug report! I'm pretty busy right now  due to other obligations, so it might be a while before I get around to it.

That said, I've been looking into testing the roles in this collection more thoroughly for some time now. Once I get around to that, I'll make sure to include a fix for this issue too!

**Comment by psyciknz** [comment]
I added:
```
- name: Other PVE repositories are disabled
  apt_repository:
    repo: "deb https://enterprise.proxmox.com/debian/pve {{ ansible_distribution_release }} {{ pve_repo_names[item] }}"
    state: absent
    filename: "{{ pve_repo_names[item] }}"
    update_cache: no
  loop: "{{ pve_disable_repos }}"
```
which removed  `https://enterprise.proxmox.com/debian/pve bookworm  pve-enterprise`

But then it also seemed to complain about:
https://enterprise.proxmox.com/debian/ceph-quincy/dists/bookworm/InRelease
